# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
source 'https://rubygems.org'
gem 'jekyll', '~>4'
gem "webrick", "~> 1.9.1"
gem "nokogiri", "~> 1.18.2"
gem "csv", "~> 3.3.2"
gem "base64", "~> 0.2.0"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.5.2"

group :jekyll_plugins do
  gem 'jekyll-redirect-from'
  gem 'jekyll-feed'
  gem 'jekyll-twitter-plugin'
end

# End Gemfile
