#!/bin/bash
# sqlline - Script to launch SQL shell
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Example:
# $ ./sqlline
# > !connect jdbc:hsqldb:res:chinook sa ''
# > select count(*) from Track;
#
# > !connect jdbc:hsqldb:res:flight FLIGHT TIGER
# > select * from "aircraft_types";
# > select count(*) from "airports";
#
# > !connect jdbc:hsqldb:res:foodmart sa ''
# > select count(*) from "foodmart"."employee";
#
# > !connect jdbc:hsqldb:res:scott SCOTT TIGER
# > select * from emp;
#
# > !connect jdbc:hsqldb:res:steelwheels steelwheels ''
# > select * from "steelwheels"."employees";

# Deduce whether we are running cygwin
case $(uname -s) in
(CYGWIN*) cygwin=true;;
(*) cygwin=;;
esac

root=$(cd "$(dirname "$(readlink $0)")"; pwd)

# Build classpath on first call. (To force rebuild, remove target/dependencies.)
if [ ! -d target/dependencies ]; then
    (
    cd $root
    ./mvnw -B -DskipTests -Dcheckfile.skip=true package
    )
fi

VM_OPTS=
if [ "$cygwin" ]; then
  # Work around https://github.com/jline/jline2/issues/62
  VM_OPTS=-Djline.terminal=jline.UnixTerminal
fi

export JAVA_OPTS=-Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl

CP=target/classes
CP=${CP}:target/test-classes
for i in target/dependencies/*.jar; do
    CP=${CP}:$i
done

exec java \
     -cp "${CP}" \
     -Xmx1g $VM_OPTS $JAVA_OPTS \
     sqlline.SqlLine "$@"

# End sqlline
