#!/bin/bash

function backup_europa {
  echo "Backup to europa"
  cd /home/jhyde/extra
  options="-avP" # add c for checksum
  echo "Copy Videos"
  rsync ${options} Videos/ $target:backup/$source/Videos
  echo "Copy Music"
  rsync ${options} Music/ $target:backup/$source/Music
  echo "Copy Downloads"
  rsync ${options} Downloads/ $target:backup/$source/Downloads
  cd /home/jhyde
  echo "Copy web"
  rsync ${options} web $target:backup/$source
  echo "Copy time-machine on Mondays"
  if [ "$TIME_MACHINE" ]; then
    rsync ${options} time-machine/ $target:backup/$source/time-machine
  fi
}

case "$1" in
(--time-machine)
  shift
  export TIME_MACHINE=true;;
(--no-time-machine)
  shift
  export TIME_MACHINE=;;
(*)
  export TIME_MACHINE=$(test $(date +%u) -eq 1 && echo true);;
esac

target="$1"
source=marmite
case "$target" in
(europa) backup_europa;;
(*) echo "unknown target '$target'"; exit 1;;
esac

# End backup
