#!/bin/bash
#
# fullMake - Performs an exhaustive build appropriate to the current project
#
LOG=/tmp/fullMake_$$.log
export GUAVA_VERSIONS="\
31.0.1-jre \
30.1.1-jre \
29.0-jre \
28.2-jre \
27.1-jre \
26.0-jre \
23.6.1-jre \
25.1-jre \
24.1.1-jre \
23.6-jre \
23.0 \
22.0 \
21.0 \
20.0 \
19.0 \
18.0 \
17.0 \
16.0.1 \
15.0 \
14.0.1 \
"
export MAX_GUAVA_VERSION=31.0.1-jre

function doAvatica {
  if [ "$1" = --allGuava ]; then
    shift
    for v in $GUAVA_VERSIONS; do
      doAvatica --guava-version $v "$@"
    done
    return
  fi
  GUAVA_VERSION=14.0.1
  if [ "$1" = --guava-version ]; then
    shift
    GUAVA_VERSION=$1
    shift
  fi
  SKIP=
  GUAVA_MAJOR=$(echo $GUAVA_VERSION | cut -d. -f 1)
  if [ "$GUAVA_MAJOR" -ge 22 -a "$GUAVA_MAJOR" -le 29 ]; then
    SKIP=" -x :standalone-server:licenseCopySpec -x :tck:licenseCopySpec -x :tck:getLicenses -x :tck:license -x :standalone-server:getLicenses -x :standalone-server:license"
  fi
  java -version &&
  echo "Guava version ${GUAVA_VERSION}" &&
  ./gradlew clean build -Pguava.version=${GUAVA_VERSION} -x rat ${SKIP} &&
  echo ::test:: &&
  ./gradlew test -x rat &&
  echo ::checkerFramework:: &&
  ./gradlew --no-parallel --no-daemon -PenableCheckerframework :core:classes :server:classes &&
  echo ::errorProne:: &&
  ./gradlew --no-parallel --no-daemon -PenableErrorprone -Pguava.version=${MAX_GUAVA_VERSION} classes &&
  echo ::done::
}

function doCalcite {
  if [ "$1" = --allGuava ]; then
    shift
    for v in $GUAVA_VERSIONS; do
      doCalcite --guava-version $v "$@"
    done
    return
  fi
  GUAVA_VERSION=19.0
  if [ "$1" = --guava-version ]; then
    shift
    GUAVA_VERSION=$1
    shift
  fi
  SKIP=
  GUAVA_MAJOR=$(echo $GUAVA_VERSION | cut -d. -f 1)
  if [ $GUAVA_MAJOR -lt 19 ]; then
    echo ::skip::
    echo "Guava version is too low"
    return
  fi
  java -version &&
  ./gradlew clean build -Pguava.version=19.0 -x rat &&
  echo ::test:: &&
  ./gradlew test -x rat &&
  echo ::checkerFramework:: &&
  ./gradlew --no-parallel --no-daemon -PenableCheckerframework :linq4j:classes :core:classes && # :arrow:classes &&
  echo ::errorProne:: &&
  ./gradlew --no-parallel --no-daemon -PenableErrorprone -Pguava.version=30.1.1-jre classes &&
  echo ::testSlow:: &&
  ./gradlew testSlow -x rat &&
  echo ::done::
}

function doMorel {
  java -version
  ./mvnw clean test javadoc:javadoc javadoc:test-javadoc
}

case $(pwd) in
(*/avatica*)
  doAvatica "$@"
  ;;
(*/calcite*)
  doCalcite "$@"
  ;;
(*/morel*)
  doMorel "$@"
  ;;
(*)
  echo "don't know how to make in $(pwd)"
  ;;
esac 2>&1 | tee $LOG
echo "See $LOG for output"

# End fullMake
