#!/bin/bash
#
# fullMake - Performs an exhaustive build appropriate to the current project
#
LOG=/tmp/fullMake_$$.log
export GUAVA_VERSIONS="\
31.0.1-jre \
30.1.1-jre \
29.0-jre \
28.2-jre \
27.1-jre \
26.0-jre \
23.6.1-jre \
25.1-jre \
24.1.1-jre \
23.6-jre \
23.0 \
22.0 \
21.0 \
20.0 \
19.0 \
18.0 \
17.0 \
16.0.1 \
15.0 \
14.0.1 \
"
export MAX_GUAVA_VERSION=31.0.1-jre

function doAvatica {
  if [ "$1" = --allGuava ]; then
    shift
    for v in $GUAVA_VERSIONS; do
      doAvatica --guava-version $v "$@"
    done
    return
  fi
  GUAVA_VERSION=14.0.1
  if [ "$1" = --guava-version ]; then
    shift
    GUAVA_VERSION=$1
    shift
  fi
  SKIP=
  GUAVA_MAJOR=$(echo $GUAVA_VERSION | cut -d. -f 1)
  if [ "$GUAVA_MAJOR" -ge 22 -a "$GUAVA_MAJOR" -le 29 ]; then
    SKIP=" -x :standalone-server:licenseCopySpec -x :tck:licenseCopySpec -x :tck:getLicenses -x :tck:license -x :standalone-server:getLicenses -x :standalone-server:license"
  fi
  SKIP="$SKIP -x rat"
  echo "::version:: $(java -version 2>&1 | head -1) guava ${GUAVA_VERSION}" &&
  ./gradlew clean build -Pguava.version=${GUAVA_VERSION} ${SKIP} &&
  echo ::test:: &&
  ./gradlew test -Pguava.version=${GUAVA_VERSION} ${SKIP} &&
  echo ::checkerFramework:: &&
  ./gradlew --no-parallel --no-daemon -PenableCheckerframework :core:classes :server:classes &&
  echo ::errorProne:: &&
  ./gradlew --no-parallel --no-daemon -PenableErrorprone -Pguava.version=${MAX_GUAVA_VERSION} classes &&
  echo ::done::
}

function doCalcite {
  if [ "$1" = --allGuava ]; then
    shift
    for v in $GUAVA_VERSIONS; do
      doCalcite --guava-version $v "$@"
    done
    return
  fi
  GUAVA_VERSION=19.0
  if [ "$1" = --guava-version ]; then
    shift
    GUAVA_VERSION=$1
    shift
  fi
  SKIP=
  GUAVA_MAJOR=$(echo $GUAVA_VERSION | cut -d. -f 1)
  if [ $GUAVA_MAJOR -lt 19 ]; then
    echo ::skip:: "(Guava version $GUAVA_VERSION is too low)"
    return
  fi
  SKIP="$SKIP -x rat"
  DO_CHECKER=$(java -version 2>&1 | awk 'FNR == 1 && ($3 ~ /.8/ || $3 ~ /.11/) {print "true"}')
  echo "::version:: $(java -version 2>&1 | head -1) guava ${GUAVA_VERSION}" &&
  ./gradlew clean build -Pguava.version=${GUAVA_VERSION} ${SKIP} &&
  echo ::test:: &&
  ./gradlew test -Pguava.version=${GUAVA_VERSION} ${SKIP} &&
  if test "$DO_CHECKER"; then
    echo ::checkerFramework::
    ./gradlew --no-parallel --no-daemon -PenableCheckerframework :linq4j:classes :core:classes # :arrow:classes
  else
    echo ::skip checkerFramework::
  fi &&
  echo ::errorProne:: &&
  ./gradlew --no-parallel --no-daemon -PenableErrorprone -Pguava.version=${MAX_GUAVA_VERSION} classes &&
  echo ::testSlow:: &&
  ./gradlew testSlow -Pguava.version=${GUAVA_VERSION} ${SKIP} &&
  echo ::done::
}

function doFiltex {
  java -version
  ./mvnw clean verify -Dcheckstyle.version=9.3 javadoc:javadoc javadoc:test-javadoc
}

function doMorel {
  java -version
  case $(java -version 2>&1 | awk 'FNR == 1 {print substr($3, 2, length($3) - 2)}') in
  (1.8.*) args="$args -Dhsqldb.version=2.5.2 -Dguava.version=19.0 -Dcheckstyle.version=9.3";;
  esac
  ./mvnw $args clean test javadoc:javadoc javadoc:test-javadoc
}

function doQuidem {
  java -version
  args=
  case $(java -version 2>&1 | awk 'FNR == 1 {print substr($3, 2, length($3) - 2)}') in
  (1.8.*) args="$args -Dhsqldb.version=2.5.2 -Dguava.version=19.0 -Dcheckstyle.version=9.3";;
  esac
  ./mvnw $args clean test javadoc:javadoc javadoc:test-javadoc
}

case $(pwd) in
(*/avatica*)
  doAvatica "$@"
  ;;
(*/calcite*)
  doCalcite "$@"
  ;;
(*/filtex*)
  doFiltex "$@"
  ;;
(*/morel*)
  doMorel "$@"
  ;;
(*/quidem*)
  doQuidem "$@"
  ;;
(*)
  echo "don't know how to make in $(pwd)"
  ;;
esac 2>&1 | tee $LOG
echo "See $LOG for output"

# End fullMake
