#!/bin/bash
# Adds a remote branch with a given name.
# Even if remote already exists, we still fetch.
#
# Bugs:
# * Should work on repository other than calcite
git remote add "$1" git@github.com:"$1"/incubator-calcite.git
git fetch "$1"
# End
