#!/bin/bash
# Prints long lines
#
# Usage:
#   longLines [files...]
#   longLines -n 70 [files...}

LENGTH=70
if [ "$1" = "-n" ]; then
  LENGTH="$2"
  shift 2
fi

gawk --assign maxLen=${LENGTH} '
length($0) > maxLen {printf "%s:%d:%s\n", FILENAME, FNR, $0}
' "$@"

# End longLines
