#!/bin/bash
# Opens a file in TextEdit (only works on macOS)
case $(uname -s) in
    (Linux) exec gedit "$@";;
    (Darwin)
        if [ ! -f "$*" ]; then
            touch "$*"
        fi
        exec open -a TextEdit "$@";;
    (*) exec vi "$@";;
esac

# End te

